### PR TITLE
Input filter to read from php://input

### PR DESCRIPTION
**Pull request by wilsonge**
To read data from patch or put requests. Required for work I'm doing on webservices

### CODE REVIEW

**Comment by mbabker** [comment]
How's this different from https://github.com/joomla-framework/input/blob/master/src/Json.php

**Comment by wilsonge** [comment]
It doesn't json_decode

**Comment by mbabker** [comment]
Write up the tests and make sure it integrates correctly with `$input->phpinput->get()` type stuff.

**Comment by wilsonge** [comment]
Tests done. My opinion is that this should be like the json - it should NOT link up with the `$input->phpinput->get()` stuff. In post request using this will lead to a duplication of data. This is specifically for PUT and DELETE requests where PHP doesn't populate the $_POST superglobal with the body contents

**Comment by mbabker** [comment]
https://github.com/joomla-framework/input/blob/2.0-dev/src/Input.php#L108

Without rewriting the getter then this will automagically work here, so it just needs to be validated that the object returns correctly and doesn't mess up other data sources.

**Pull request closed without merging**
